package edu.ucdenver.ccp.knowtator.view;

import edu.ucdenver.ccp.knowtator.KnowtatorController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class GraphViewDialog extends JDialog {
	private JPanel contentPane;
	private GraphView graphView;
	private KnowtatorController controller;

	GraphViewDialog(KnowtatorController controller) {
		this.controller = controller;
		$$$setupUI$$$();
		setSize(new Dimension(800, 800));
		setLocationRelativeTo(controller.getView());

		setContentPane(contentPane);
		setModal(false);

		setJMenuBar(new JMenuBar());
		GraphMenu graphMenu = new GraphMenu(controller);
		getJMenuBar().add(graphMenu);

		// call onCancel() when cross is clicked
		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(
				new WindowAdapter() {
					public void windowClosing(WindowEvent e) {
						onCancel();
					}
				});

		// call onCancel() on ESCAPE
		contentPane.registerKeyboardAction(
				e -> onCancel(),
				KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
				JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
	}

	private void onCancel() {
		// add your code here if necessary
		dispose();
	}

	private void createUIComponents() {
		graphView = new GraphView(this, controller);
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
	 * call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		contentPane = new JPanel();
		contentPane.setLayout(new BorderLayout(0, 0));
		contentPane.add(graphView.$$$getRootComponent$$$(), BorderLayout.CENTER);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}

	//    public static void main(String[] args) {
	//        GraphViewDialog dialog = new GraphViewDialog();
	//        dialog.pack();
	//        dialog.setVisible(true);
	//        System.exit(0);
	//    }
}
